# Generated by Django 5.0.1 on 2024-01-29 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_value_cart_cart_value_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 5, 12, 37, 71895, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
