# Generated by Django 5.0.1 on 2024-01-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_session_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='items',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(through='myapp.CartDetails', to='myapp.product'),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
